# Generated by Django 3.1.1 on 2020-09-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='org_name', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('role', models.CharField(help_text='position_or_job', max_length=100)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(help_text='org_name', max_length=100)),
                ('name_degree', models.CharField(help_text='title_name', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='name_of_project', max_length=200)),
                ('description', models.CharField(help_text='project_description', max_length=600, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='user_name', max_length=100)),
                ('surname', models.CharField(help_text='user_surname', max_length=100)),
                ('birthdate', models.DateField()),
                ('phone', models.PositiveIntegerField(help_text='phone_number')),
                ('mail', models.EmailField(help_text='email_account', max_length=254)),
                ('career', models.ManyToManyField(blank=True, related_name='carrers', to='portfolioapp.Career')),
                ('education', models.ManyToManyField(blank=True, related_name='education', to='portfolioapp.Education')),
                ('project', models.ManyToManyField(blank=True, related_name='projects', to='portfolioapp.Project')),
            ],
        ),
    ]
