# Generated by Django 3.1.1 on 2020-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_auto_20200913_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='career',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AddField(
            model_name='career',
            name='user',
            field=models.ManyToManyField(null=True, to='portfolioapp.User'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ManyToManyField(null=True, to='portfolioapp.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(null=True, to='portfolioapp.User'),
        ),
    ]
