# Generated by Django 3.1.1 on 2020-09-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20200913_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.ManyToManyField(null=True, to='portfolioapp.Career'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(null=True, to='portfolioapp.Education'),
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(null=True, to='portfolioapp.Project'),
        ),
    ]
