# Generated by Django 3.1.1 on 2020-09-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_auto_20200915_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.ManyToManyField(blank=True, null=True, to='portfolioapp.Career'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='portfolioapp.Education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='portfolioapp.Project'),
        ),
    ]
