# Generated by Django 3.1.1 on 2020-09-17 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_auto_20200915_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1, max_length=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='knowledge',
            field=models.ManyToManyField(blank=True, null=True, to='portfolioapp.Knowledge'),
        ),
    ]
