# Generated by Django 3.1.1 on 2020-09-17 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_auto_20200917_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
